### ISSUE TITLE
Fix photo display

### ISSUE THREAD

**Issue by mae1884** [mae1884/nipper_ny#3]
Again, trying to fix how the theme originally appears in albanycountypost.com, the CMS allows for three different ways of displaying an in-body image and the Gatsby build doesn't allow this. 

Please show images as intended via the CMS, and style the cutlines to match.

**Comment by mae1884** [comment]
@marcomiduri  you were probably thinking of this one

**Comment by mae1884** [comment]
@marcomiduri  https://www.awesomescreenshot.com/video/3401888?key=e88169dca010397085ca5b5cdb705ace

**Comment by marcomiduri** [comment]
@mae1884 Thanks for sharing this record and it's very clear to me.

**Comment by marcomiduri** [comment]
@mae1884 Please check this update. https://6078d2536240f10007a786fd--elegant-bhabha-d87108.netlify.app/

I also moved the featured image under the author profile. 

Thanks
