### ISSUE TITLE
In-article item layout

### ISSUE THREAD

**Issue by mae1884** [mae1884/nipper_ny#6]
In article/post: Display tag above headline. Headline above post, followed by subhead and author information (photo, name, date, time) linking to Discourse profile. This layout sequence is meant to simply describe the albanycountypost.com (screenshot below)

![image](https://user-images.githubusercontent.com/61389274/114321751-f98cb780-9ae1-11eb-8ae9-5fc1fdd0274c.png)

**Comment by marcomiduri** [comment]
@mae1884 How can I get the Discourse profile link?

**Comment by mae1884** [comment]
> 
> 
> @mae1884 How can I get the Discourse profile link?
@marcomiduri it looks like you've done a nice job. Thank you. But the order isn't quite the same. Can you put the tag, headline, subhead, and author information ABOVE the first photo?
